### ISSUE TITLE
stackcollapse-hpl fails with "Exception: Unexpected marker: 21 at offset 14"

### ISSUE THREAD

**Issue by tgrabiec** [cykl/hprof2flamegraph#3]
I get the following error when trying to parse a hpl file generated by honest-profiler (version d505d540ad09516ede804e7d1aa34a889f266780):

```
stackcollapse-hpl slow2 > output-folded.txt
Traceback (most recent call last):
  File "/usr/local/bin/stackcollapse-hpl", line 9, in <module>
    load_entry_point('hprof2flamegraph==0.0.2', 'console_scripts', 'stackcollapse-hpl')()
  File "/usr/local/lib/python3.4/dist-packages/stackcollapse_hpl.py", line 110, in main
    (traces, methods) = parse_hpl(filename)
  File "/usr/local/lib/python3.4/dist-packages/stackcollapse_hpl.py", line 72, in parse_hpl
    raise Exception("Unexpected marker: %s at offset %s" % (marker, fh.tell()))
Exception: Unexpected marker: 21 at offset 14
```

**Comment by tgrabiec** [comment]
Using https://github.com/RichardWarburton/honest-profiler/blob/master/src/main/java/com/insightfullogic/honest_profiler/ports/console/FlameGraphDumperApplication.java on the same file seems to work.

**Comment by cykl** [comment]
Hi Tomasz,

Thanks for the report. It has been a while since I last used honest-profiler (mainly using perf & flight recorder now). Work is piling up, but I will try to find some time next week to investigate whether it's a bug or if they evolved hpl format.

**Comment by cykl** [comment]
I just quickly troubleshooted the issue. This is due to e9b13fcea517af8b1a93be3e196591d1b466a723 which introduced a new type of log events. I will add support for this new log event soon.

**Comment by cykl** [comment]
I just pushed a fix into the master. Could you test it ?
